#!/usr/bin/env python3
"""
Night Characterization
======================
Computes per-night modulation quality metrics from nadirs.csv, phases.csv,
and plateaus.csv (generated by plateau_analysis.py).

Output: night_characteristics.csv

Usage:
    python3 night_characterization.py
    python3 night_characterization.py --data-dir ../hrphases --out-dir .
"""

import sys
from pathlib import Path
from datetime import date

import numpy as np
import pandas as pd
from scipy import stats as sp_stats


# ---------------------------------------------------------------------------
# Metric computation
# ---------------------------------------------------------------------------
def characterize_night(night_str, pn, phn, ndn):
    """
    Compute all modulation quality metrics for one night.

    Parameters
    ----------
    night_str : str  — night date as YYYY-MM-DD
    pn  : DataFrame  — plateaus for this night
    phn : DataFrame  — phases for this night
    ndn : DataFrame  — nadirs for this night

    Returns
    -------
    dict or None if insufficient data
    """
    n_date = date.fromisoformat(night_str)

    if len(pn) < 2 or len(phn) < 2 or len(ndn) < 2:
        return None

    max_d = pn["stack_depth"].max()
    base_level = pn["level"].min()
    top_level = pn["level"].max()
    total_range = top_level - base_level

    # --- Plateau metrics ---

    # Duration distribution across stack depths
    dur_per_depth = pn.groupby("stack_depth")["duration_min"].sum()
    dur_cv = (
        dur_per_depth.std() / dur_per_depth.mean()
        if len(dur_per_depth) >= 2 and dur_per_depth.mean() > 0
        else np.nan
    )

    # Count distribution across stack depths
    count_per_depth = pn.groupby("stack_depth").size()
    count_cv = (
        count_per_depth.std() / count_per_depth.mean()
        if len(count_per_depth) >= 2 and count_per_depth.mean() > 0
        else np.nan
    )

    # Modulation breaks: plateaus whose duration deviates >2x from
    # the mean duration at adjacent stack levels
    breaks = 0
    for _, p in pn.iterrows():
        d = p["stack_depth"]
        neighbors = pn[
            (pn["stack_depth"] == d - 1) | (pn["stack_depth"] == d + 1)
        ]
        if len(neighbors) == 0:
            continue
        neighbor_mean = neighbors["duration_min"].mean()
        if neighbor_mean > 0:
            ratio = p["duration_min"] / neighbor_mean
            if ratio < 0.5 or ratio > 2.0:
                breaks += 1
    break_frac = breaks / len(pn)

    # Level spacing regularity
    levels = sorted(pn["level"].unique())
    if len(levels) >= 3:
        spacings = np.diff(levels)
        spacing_cv = (
            np.std(spacings) / np.mean(spacings)
            if np.mean(spacings) > 0
            else np.nan
        )
    else:
        spacing_cv = np.nan

    # Stack symmetry: mean duration upper half / mean duration lower half
    if max_d >= 2:
        mid = max_d / 2
        lower = pn[pn["stack_depth"] <= mid]["duration_min"]
        upper = pn[pn["stack_depth"] > mid]["duration_min"]
        stack_sym = (
            upper.mean() / lower.mean()
            if len(lower) > 0
            and len(upper) > 0
            and lower.mean() > 0
            else np.nan
        )
    else:
        stack_sym = np.nan

    # Intra-depth duration consistency
    intra_cvs = []
    for d in range(max_d + 1):
        at_d = pn[pn["stack_depth"] == d]
        if len(at_d) >= 2 and at_d["duration_min"].mean() > 0:
            intra_cvs.append(
                at_d["duration_min"].std() / at_d["duration_min"].mean()
            )
    intra_dur_cv = np.mean(intra_cvs) if intra_cvs else np.nan

    # High plateau fractions (ANS autonomy markers)
    total_sleep = pn["duration_min"].max()
    high = pn[pn["level"] > base_level + 5]
    vhigh = pn[pn["level"] > base_level + 8]

    frac_high = (
        high["duration_min"].sum() / total_sleep
        if total_sleep > 0
        else np.nan
    )
    frac_vhigh = (
        vhigh["duration_min"].sum() / total_sleep
        if total_sleep > 0
        else np.nan
    )

    # Depth counts
    n_d1 = len(pn[pn["stack_depth"] >= 1])
    n_d2 = len(pn[pn["stack_depth"] >= 2])
    n_d3 = len(pn[pn["stack_depth"] >= 3])

    # --- Phase metrics ---

    n_phases = len(phn)
    mean_phase_dur = phn["duration_min"].mean()
    phase_dur_cv = (
        phn["duration_min"].std() / phn["duration_min"].mean()
        if phn["duration_min"].mean() > 0
        else np.nan
    )
    mean_phase_std = phn["hr_std"].mean()

    # Phase half-night comparison
    half = n_phases // 2
    if half >= 2:
        first_half_std = phn.iloc[:half]["hr_std"].mean()
        second_half_std = phn.iloc[half:]["hr_std"].mean()
        std_ratio = (
            second_half_std / first_half_std
            if first_half_std > 0
            else np.nan
        )
        first_half_dur = phn.iloc[:half]["duration_min"].mean()
        second_half_dur = phn.iloc[half:]["duration_min"].mean()
        dur_ratio = (
            second_half_dur / first_half_dur
            if first_half_dur > 0
            else np.nan
        )
    else:
        std_ratio = np.nan
        dur_ratio = np.nan

    # --- Nadir metrics ---

    n_nadirs = len(ndn)
    nadir_mean = ndn["mhr10"].mean()
    nadir_std = ndn["mhr10"].std() if n_nadirs >= 2 else np.nan
    nadir_range = (
        ndn["mhr10"].max() - ndn["mhr10"].min()
        if n_nadirs >= 2
        else np.nan
    )

    # Nadir slope: regression of nadir MHR10 values over the night
    if n_nadirs >= 3:
        sl, _, _, p_val, _ = sp_stats.linregress(
            np.arange(n_nadirs), ndn["mhr10"].values
        )
        nadir_slope = sl
    else:
        nadir_slope = np.nan

    return {
        "night_date": night_str,
        # Plateau structure
        "n_plateaus": len(pn),
        "max_depth": max_d,
        "base_level": round(base_level, 1),
        "top_level": round(top_level, 1),
        "total_range": round(total_range, 1),
        # Modulation quality
        "dur_cv": round(dur_cv, 3) if not np.isnan(dur_cv) else np.nan,
        "count_cv": round(count_cv, 3) if not np.isnan(count_cv) else np.nan,
        "break_frac": round(break_frac, 3),
        "spacing_cv": round(spacing_cv, 3) if not np.isnan(spacing_cv) else np.nan,
        "stack_symmetry": round(stack_sym, 3) if not np.isnan(stack_sym) else np.nan,
        "intra_dur_cv": round(intra_dur_cv, 3) if not np.isnan(intra_dur_cv) else np.nan,
        # ANS autonomy
        "frac_high": round(frac_high, 3) if not np.isnan(frac_high) else np.nan,
        "frac_vhigh": round(frac_vhigh, 3) if not np.isnan(frac_vhigh) else np.nan,
        "n_d1": n_d1,
        "n_d2": n_d2,
        "n_d3": n_d3,
        # Phase metrics
        "n_phases": n_phases,
        "mean_phase_dur": round(mean_phase_dur, 1),
        "phase_dur_cv": round(phase_dur_cv, 3) if not np.isnan(phase_dur_cv) else np.nan,
        "mean_phase_std": round(mean_phase_std, 2),
        "std_ratio_2nd_1st": round(std_ratio, 3) if not np.isnan(std_ratio) else np.nan,
        "dur_ratio_2nd_1st": round(dur_ratio, 3) if not np.isnan(dur_ratio) else np.nan,
        # Nadir metrics
        "n_nadirs": n_nadirs,
        "nadir_mean": round(nadir_mean, 1),
        "nadir_std": round(nadir_std, 2) if not np.isnan(nadir_std) else np.nan,
        "nadir_range": round(nadir_range, 1) if not np.isnan(nadir_range) else np.nan,
        "nadir_slope": round(nadir_slope, 3) if not np.isnan(nadir_slope) else np.nan,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    script_dir = Path(__file__).parent
    data_dir = script_dir
    out_dir = script_dir

    if "--data-dir" in sys.argv:
        data_dir = Path(sys.argv[sys.argv.index("--data-dir") + 1])
    if "--out-dir" in sys.argv:
        out_dir = Path(sys.argv[sys.argv.index("--out-dir") + 1])
    out_dir.mkdir(parents=True, exist_ok=True)

    # Load CSVs
    nadirs = pd.read_csv(data_dir / "nadirs.csv", dtype={"night_date": str})
    phases = pd.read_csv(data_dir / "phases.csv", dtype={"night_date": str})
    plateaus = pd.read_csv(data_dir / "plateaus.csv", dtype={"night_date": str})

    nights = sorted(
        set(nadirs["night_date"]) | set(phases["night_date"]) | set(plateaus["night_date"])
    )
    print(f"Processing {len(nights)} nights...")

    rows = []
    for night_str in nights:
        pn = plateaus[plateaus["night_date"] == night_str]
        phn = phases[phases["night_date"] == night_str]
        ndn = nadirs[nadirs["night_date"] == night_str]
        result = characterize_night(night_str, pn, phn, ndn)
        if result:
            rows.append(result)

    df = pd.DataFrame(rows)
    out_path = out_dir / "night_characteristics.csv"
    df.to_csv(out_path, index=False)
    print(f"Output: {out_path} ({len(df)} nights)")

    # Summary
    print(f"\nMetric ranges:")
    for col in df.columns:
        if col == "night_date":
            continue
        vals = df[col].dropna()
        if len(vals) == 0:
            continue
        print(f"  {col:<25s} {vals.median():8.2f} (IQR {vals.quantile(0.25):.2f}–{vals.quantile(0.75):.2f})")


if __name__ == "__main__":
    main()
