#!/usr/bin/env python3
"""
Render nadir and plateau charts for a given night.

Usage:
    python3 render_charts.py 2024-12-13
    python3 render_charts.py 2024-12-13 --out-dir ./charts

Reads:
    - Gadgetbridge DB (for raw HR + MHR10)
    - nadirs.csv, plateaus.csv (generated by plateau_analysis.py)
    - template_nadirs.html, template_plateaus.html

Outputs:
    - nadirs_YYYY-MM-DD.html
    - plateaus_YYYY-MM-DD.html
"""

import sys
import json
import sqlite3
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd

TZ = ZoneInfo("Europe/Berlin")
MHR_WINDOW = 10


def find_file(name, script_dir):
    for p in [script_dir / name, Path("/mnt/user-data/uploads") / name,
              Path("/home/claude/gb") / name, Path("../") / name]:
        if p.exists():
            return p
    return None


def load_night_hr(db_path, night_date):
    """Load raw HR for the sleep session waking on night_date."""
    con = sqlite3.connect(str(db_path))
    sleep = pd.read_sql(
        "SELECT TIMESTAMP/1000 as sleep_start, WAKEUP_TIME/1000 as sleep_end, "
        "TOTAL_DURATION FROM XIAOMI_SLEEP_TIME_SAMPLE WHERE TOTAL_DURATION > 60", con)
    sleep["end_dt"] = pd.to_datetime(sleep["sleep_end"], unit="s", utc=True).dt.tz_convert(TZ)
    sleep["wake_date"] = sleep["end_dt"].dt.date

    target = datetime.strptime(night_date, "%Y-%m-%d").date()
    sessions = sleep[sleep["wake_date"] == target]
    if sessions.empty:
        con.close()
        return None, None, None
    row = sessions.sort_values("TOTAL_DURATION", ascending=False).iloc[0]

    act = pd.read_sql(
        f"SELECT TIMESTAMP, HEART_RATE FROM XIAOMI_ACTIVITY_SAMPLE "
        f"WHERE HEART_RATE > 0 AND HEART_RATE < 200 "
        f"AND TIMESTAMP >= {int(row['sleep_start'])} AND TIMESTAMP <= {int(row['sleep_end'])}",
        con)
    con.close()
    act = act.sort_values("TIMESTAMP").reset_index(drop=True)

    hr = act["HEART_RATE"].values.astype(float)
    ts = act["TIMESTAMP"].values.astype(float)
    times = [pd.Timestamp(t, unit="s", tz="UTC").tz_convert(TZ).strftime("%H:%M") for t in ts]
    mhr10 = pd.Series(hr).rolling(MHR_WINDOW, center=True, min_periods=MHR_WINDOW // 2 + 1).mean().values

    return hr, mhr10, times


def build_nadir_data(hr, mhr10, times, nadirs_df, night_date):
    """Build JSON data dict for nadir template."""
    night_nadirs = nadirs_df[nadirs_df["night_date"] == night_date]
    nadir_times = night_nadirs["time"].tolist()

    # Map nadir times to indices in the times array
    nadir_indices = []
    for nt in nadir_times:
        matches = [i for i, t in enumerate(times) if t == nt]
        if matches:
            nadir_indices.append(matches[0])

    m10_clean = [round(float(v), 1) if not np.isnan(v) else None for v in mhr10]
    y_vals = [v for v in m10_clean if v is not None]
    y_min = int(min(y_vals) // 5) * 5 - 2
    y_max = int(max(y_vals) // 5 + 1) * 5 + 2

    return {
        "t": times,
        "hr": [int(h) for h in hr],
        "m10": m10_clean,
        "nadir_indices": nadir_indices,
        "y_min": y_min,
        "y_max": y_max,
    }


def build_plateau_data(mhr10, times, nadirs_df, plateaus_df, night_date):
    """Build JSON data dict for plateau template."""
    night_nadirs = nadirs_df[nadirs_df["night_date"] == night_date]
    night_plateaus = plateaus_df[plateaus_df["night_date"] == night_date]

    # Build time→index lookup
    time_to_idx = {}
    for i, t in enumerate(times):
        if t not in time_to_idx:
            time_to_idx[t] = i

    # Map nadirs to indices
    nadir_time_to_idx = {}
    for _, row in night_nadirs.iterrows():
        if row["time"] in time_to_idx:
            nadir_time_to_idx[row["time"]] = time_to_idx[row["time"]]

    # Build plateau list with nadir indices
    plateau_list = []
    for _, pl in night_plateaus.iterrows():
        # Find which nadirs belong to this plateau:
        # nadirs whose time falls within [start_time, end_time] and whose
        # mhr10 value is within 1.5 of the plateau level
        pl_nadirs = []
        for _, nd in night_nadirs.iterrows():
            if nd["time"] in nadir_time_to_idx:
                idx = nadir_time_to_idx[nd["time"]]
                # Check if nadir is within plateau time span
                if nd["time"] >= pl["start_time"] and nd["time"] <= pl["end_time"]:
                    if abs(nd["mhr10"] - pl["level"]) < 2.0:
                        pl_nadirs.append(idx)

        # Fallback: if no nadirs matched, find closest nadir to the level
        if not pl_nadirs:
            best = None
            best_dist = float("inf")
            for _, nd in night_nadirs.iterrows():
                if nd["time"] in nadir_time_to_idx:
                    d = abs(nd["mhr10"] - pl["level"])
                    if d < best_dist:
                        best_dist = d
                        best = nadir_time_to_idx[nd["time"]]
            if best is not None:
                pl_nadirs = [best]

        plateau_list.append({
            "level": round(float(pl["level"]), 1),
            "n_nadirs": int(pl["n_nadirs"]),
            "stack_depth": int(pl["stack_depth"]),
            "nadir_indices": pl_nadirs,
        })

    m10_clean = [round(float(v), 1) if not np.isnan(v) else None for v in mhr10]
    y_vals = [v for v in m10_clean if v is not None]
    y_min = int(min(y_vals) // 5) * 5 - 2
    y_max = int(max(y_vals) // 5 + 1) * 5 + 2

    return {
        "t": times,
        "m10": m10_clean,
        "plateaus": plateau_list,
        "y_min": y_min,
        "y_max": y_max,
    }


def render(template_path, data_json, night_date, out_path):
    """Replace placeholders and write HTML."""
    tmpl = template_path.read_text(encoding="utf-8")
    html = tmpl.replace("{{NIGHT_DATE}}", night_date)
    html = html.replace("{{DATA_JSON}}", json.dumps(data_json, separators=(",", ":")))
    out_path.write_text(html, encoding="utf-8")
    print(f"  → {out_path}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 render_charts.py YYYY-MM-DD [--out-dir DIR]")
        sys.exit(1)

    night_date = sys.argv[1]
    out_dir = Path(".")
    if "--out-dir" in sys.argv:
        out_dir = Path(sys.argv[sys.argv.index("--out-dir") + 1])
    out_dir.mkdir(parents=True, exist_ok=True)

    script_dir = Path(__file__).parent

    # Find files
    db_path = find_file("Gadgetbridge", script_dir)
    if db_path is None:
        print("ERROR: Gadgetbridge DB not found", file=sys.stderr)
        sys.exit(1)

    nadirs_csv = find_file("nadirs.csv", script_dir)
    plateaus_csv = find_file("plateaus.csv", script_dir)
    tmpl_nadirs = find_file("template_nadirs.html", script_dir)
    tmpl_plateaus = find_file("template_plateaus.html", script_dir)

    for name, path in [("nadirs.csv", nadirs_csv), ("plateaus.csv", plateaus_csv),
                        ("template_nadirs.html", tmpl_nadirs), ("template_plateaus.html", tmpl_plateaus)]:
        if path is None:
            print(f"ERROR: {name} not found", file=sys.stderr)
            sys.exit(1)

    # Load data
    hr, mhr10, times = load_night_hr(db_path, night_date)
    if hr is None:
        print(f"ERROR: No sleep session found for {night_date}", file=sys.stderr)
        sys.exit(1)

    nadirs_df = pd.read_csv(str(nadirs_csv), dtype={"night_date": str})
    plateaus_df = pd.read_csv(str(plateaus_csv), dtype={"night_date": str})

    print(f"Rendering charts for {night_date} ({len(hr)} HR samples)")

    # Nadir chart
    nadir_data = build_nadir_data(hr, mhr10, times, nadirs_df, night_date)
    render(tmpl_nadirs, nadir_data, night_date,
           out_dir / f"nadirs_{night_date}.html")

    # Plateau chart
    plateau_data = build_plateau_data(mhr10, times, nadirs_df, plateaus_df, night_date)
    render(tmpl_plateaus, plateau_data, night_date,
           out_dir / f"plateaus_{night_date}.html")


if __name__ == "__main__":
    main()
